apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "marklogic.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marklogic.labels" . | nindent 4 }}
data:
  MARKLOGIC_BOOTSTRAP_HOST: {{ include "marklogic.fullname" . }}-0
  MARKLOGIC_FQDN_SUFFIX: {{ include "marklogic.headlessURL" . }}
  MARKLOGIC_INIT: "true"
  MARKLOGIC_JOIN_CLUSTER: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.logging.configMapName }}
  namespace: {{ .Release.Namespace }}
data:
  fluent-bit.conf: |
      [SERVICE]
        Flush 5
        Log_Level info
        Daemon off
        Parsers_File parsers.conf

      @INCLUDE inputs.conf
      @INCLUDE filters.conf
      @INCLUDE outputs.conf

  inputs.conf: |
      {{- if .Values.logging.trackFiles.errorLogs }}
      [INPUT]
        Name tail
        Path {{ .Values.persistence.mountPath }}/Logs/*Error*
        Read_from_head true
        Tag kube.marklogic.logs.error
        Path_Key path
      {{- end }}
      
      {{- if .Values.logging.trackFiles.accessLogs }}
      [INPUT]
        Name tail
        Path {{ .Values.persistence.mountPath }}/Logs/*Access*
        Read_from_head true
        tag kube.marklogic.logs.access
        Path_Key path
      {{- end }}

      {{- if .Values.logging.trackFiles.requestLogs }}
      [INPUT]
        Name tail
        Path {{ .Values.persistence.mountPath }}/Logs/*Request*
        Read_from_head true
        tag kube.marklogic.logs.request
        Path_Key path
      {{- end }}

      {{- if .Values.logging.trackFiles.crashLogs }}
      [INPUT]
        Name tail
        Path {{ .Values.persistence.mountPath }}/Logs/CrashLog.txt
        Read_from_head true
        tag kube.marklogic.logs.crash
        Path_Key path
      {{- end }}

      {{- if .Values.logging.trackFiles.auditLogs }}
      [INPUT]
        Name tail
        Path {{ .Values.persistence.mountPath }}/Logs/AuditLog.txt
        Read_from_head true
        tag kube.marklogic.logs.audit
        Path_Key path
      {{- end }}

  outputs.conf: |
      # Example output config for ElasticSearch output
      # [OUTPUT]
      #   Name es
      #   Match *
      #   Host {{ .Values.logging.host }}
      #   Port {{ .Values.logging.port }}
      #   HTTP_User {{ .Values.logging.username }}
      #   HTTP_Passwd {{ .Values.logging.password }}
      # Configure desired output below, documentation on how to set up output can be found here
      # https://docs.fluentbit.io/manual/pipeline/outputs

  filters.conf: |
      # Enrich Logs
      [FILTER]
        Name modify
        Match *
        Add pod ${POD_NAME}
        Add namespace {{ .Release.Namespace }}

      [FILTER]
        Name modify
        Match kube.marklogic.logs.error
        Add tag kube.marklogic.logs.error

      [FILTER]
        Name modify
        Match kube.marklogic.logs.access
        Add tag kube.marklogic.logs.access

      [FILTER]
        Name modify
        Match kube.marklogic.logs.request
        Add tag kube.marklogic.logs.request

      [FILTER]
        Name modify
        Match kube.marklogic.logs.audit
        Add tag kube.marklogic.logs.audit

      [FILTER]
        Name modify
        Match kube.marklogic.logs.crash
        Add tag kube.marklogic.logs.crash

      # Parse Logs
      [FILTER]
        Name parser
        Match kube.marklogic.logs.error
        Key_Name log
        Parser error_parser
        Reserve_Data On

      [FILTER]
        Name parser
        Match kube.marklogic.logs.access
        Key_Name log
        Parser access_parser
        Reserve_Data On

      [FILTER]
        Name parser
        Match kube.marklogic.logs.request
        Key_Name log
        Parser json_parser
        Reserve_Data On

  parsers.conf: |
      [PARSER]
        Name error_parser
        Format regex
        Regex ^(?<time>(.+?)(?=[a-zA-Z]))(?<log_level>(.+?)(?=:))(.+?)(?=[a-zA-Z])(?<log>.*)
        Time_Key time 
        Time_Format %Y-%m-%d %H:%M:%S.%L

      [PARSER]
        Name access_parser
        Format regex
        Regex ^(?<host>[^ ]*)(.+?)(?<=\- )(?<user>(.+?)(?=\[))(.+?)(?<=\[)(?<time>(.+?)(?=\]))(.+?)(?<=")(?<request>[^\ ]+[^\"]+)(.+?)(?=\d)(?<response_code>[^\ ]*)(.+?)(?=\d|-)(?<response_obj_size>[^\ ]*)(.+?)(?=")(?<request_info>.*)
        Time_Key time 
        Time_Format %d/%b/%Y:%H:%M:%S %z

      [PARSER]
        Name json_parser
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S%z
