apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "marklogic.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marklogic.labels" . | nindent 4 }}
data:
  MARKLOGIC_BOOTSTRAP_HOST: {{ include "marklogic.fullname" . }}-0
  MARKLOGIC_FQDN_SUFFIX: {{ include "marklogic.headlessURL" . }}
  MARKLOGIC_INIT: "true"
  MARKLOGIC_JOIN_CLUSTER: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.logging.configMapName }}
  namespace: {{ .Release.Namespace }}
data:
  fluent-bit.conf: |
      [SERVICE]
        Flush  5
        Log_Level  info
        Daemon  off
      
      [INPUT]
        Name  tail
        Path  {{ .Values.persistence.mountPath }}/Logs/*
        Tag  marklogic-logs
        Path_Key  path

      [OUTPUT]
        Name  es
        Match  *
        Host  {{ .Values.logging.host }}
        Port  {{ .Values.logging.port }}
        HTTP_User  {{ .Values.logging.username }}
        HTTP_Passwd  {{ .Values.logging.password }}