apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "marklogic.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marklogic.labels" . | nindent 4 }}
data:
{{- if ne .Values.bootstrapClusterName "" }}
  MARKLOGIC_BOOTSTRAP_HOST: {{ .Values.bootstrapClusterName }}
  MARKLOGIC_JOIN_CLUSTER: "true"
{{- else }}
  MARKLOGIC_BOOTSTRAP_HOST: {{ include "marklogic.fullname" . }}-0
  MARKLOGIC_JOIN_CLUSTER: "false"
{{- end }}
  MARKLOGIC_FQDN_SUFFIX: {{ include "marklogic.headlessURL" . }}
  MARKLOGIC_INIT: "true"
